### ISSUE TITLE
FEATURE REQUEST: option to have the "post to Bluesky" box checked by default

### ISSUE THREAD

**Issue by StianOby** [rathlinus/Wordpress-Bluesky-Plugin#3]
Using version 1.2, every new post was automatically pushed to Bluesky. After we upgraded to version 1.4, there is now a checkbox under the text editor labled "Post to Bluesky" that must be checked manually for a new WP post to be pushed to Bluesky.

I suggest adding an option in the settings where one could choose whether to have this box checked by default.

**Comment by rathlinus** [comment]
The box should be ticked by default, i will check if there is a bug.

**Comment by StianOby** [comment]
Perhaps it was due to me upgrading from 1.2?

I was able to update, keeping the settings, by uninstalling 1.2 and then installing 1.4 through the control panel (manual install, by uploading zip file in the dashboard).

Regardless of what the default setting is on first install, having an option in the settings to choose the default seems useful.

**Comment by rathlinus** [comment]
Ive added this in 1.5
