### ISSUE TITLE
Bluesky posts are published at an incorrect time

### ISSUE THREAD

**Issue by nickheer** [rathlinus/Wordpress-Bluesky-Plugin#6]
Hi there!

Great work on this plugin, Linus, and thank you for building it.

The issue I am having is that [this Bluesky post](https://bsky.app/profile/pxlnv.bsky.social/post/3kkrtekjcjp2i) was published at 15:45 local time, but it is displayed at 08:45 local time. 

I believe this is possibly duplicating the time zone offset. I live in (and my website is set to) UTC –7 (currently). The difference between the time I selected "Publish to Bluesky" using this plugin and the timestamp on the Bluesky post is also 7 hours.

I am using WordPress 6.4.3 with v 1.5 of this plugin. I am using WP-Cron. I do not have "enable delay" turned on.

I hope this is helpful!

Nick

**Comment by rathlinus** [comment]
Good Evening,

the Plugin should work with and without a cronjob. The WP-Cron hits the plugin every time someone visits a site. So if no one visites your site for lets say a day, the Posts will not be published on that day.

I am not sure what happend to your post. Do you have your Logs enabled? And if, could you post them?

Linus

**Comment by nickheer** [comment]
Hi Linus,

I'm afraid that, even with logging enabled, they may not be of much use. I posted two things today and here is the log:

```
[08-Feb-2024 00:16:37 UTC] No featured image found for post ID 37653, checking for fallback image.
[08-Feb-2024 00:16:37 UTC] No fallback image set, using placeholder.
[08-Feb-2024 00:56:27 UTC] No featured image found for post ID 37658, checking for fallback image.
[08-Feb-2024 00:56:27 UTC] No fallback image set, using placeholder.
```

Not the most useful logs in terms of highlighting any errors, but perhaps useful for the timecodes. My site is set to UTC–7, so these were posted at 17:16 and 17:56 on February 7.

However, the automatic Bluesky posts were again offset by seven hours: https://bsky.app/profile/pxlnv.bsky.social/post/3kkuiwtku6c24 , https://bsky.app/profile/pxlnv.bsky.social/post/3kkul633ufs23

If there are logs I can enable for the plugin I would be happy to do so. 

Thanks for looking into this,
Nick

**Comment by rathlinus** [comment]
Ah, it is Probably because of this:

```php
            'record' => [
                'text' => $post_title,
                'createdAt' => current_time('Y-m-d\TH:i:s\Z'),
                'embed' => $embed_card,
            ],
``` 
This returns the Current time in your Timezone, but Bluesky thinks that it is UTC±0 so it shows that the post was made several hours ago. 

We can fix that by using:

```php
gmdate('Y-m-d\TH:i:s\Z')

//instead of

current_time('Y-m-d\TH:i:s\Z')
```
